/**
 * Centralized fallback mock data for Parent Portal
 * Used when MongoDB is offline or running in demo mode
 */

export const FALLBACK_PARENT = {
  _id: '66789abcdef0123456789abc',
  userId: '66789abcdef0123456789abc',
  fatherName: 'Suresh',
  fatherOccupation: 'Software Engineering Director',
  fatherContact: '+91 98765 43210',
  motherName: 'Latha ',
  motherOccupation: 'Architect & Urban Designer',
  motherContact: '+91 98765 43211',
  guardianName: 'Vikram & Priya Sharma',
  guardianContact: '+91 98765 43210',
  primaryEmail: 'parent@school.com',
  address: 'House 42, Palm Meadows, Whitefield, Bengaluru, Karnataka 560066',
  whatsappNumber: '+91 98765 43210',
  createdAt: new Date('2024-06-01T00:00:00.000Z'),
  updatedAt: new Date('2026-09-20T00:00:00.000Z'),
};

export const FALLBACK_CHILDREN = [
  {
    _id: 'c10101010101010101010101',
    firstName: 'Aarav',
    lastName: 'Sharma',
    admissionNumber: 'GGPS-2024-089',
    rollNumber: '14',
    grade: 'LKG',
    section: 'A',
    classId: { _id: 'class_lkg_id', name: 'LKG' },
    sectionId: { _id: 'sec_lkg_a_id', name: 'Section A' },
    bloodGroup: 'B+',
    emergencyContact: '+91 98765 43210',
    medicalNotes: 'Mild seasonal peanut allergy; inhaler not required.',
    studentPhoto: '/aarav-hero-student.jpg',
    enrollmentDate: new Date('2024-06-15T00:00:00.000Z'),
    status: 'Active',
    parentId: '66789abcdef0123456789abc',
    teacherName: 'Ms. Ananya Roy',
    attendanceRate: 92,
    pendingHomework: 3,
    feesDue: 8500,
    recentActivity: 'Numbers & Counting tactile play',
  },
  {
    _id: 'c20202020202020202020202',
    firstName: 'Ananya',
    lastName: 'Sharma',
    admissionNumber: 'GGPS-2022-042',
    rollNumber: '07',
    grade: 'Class 3',
    section: 'B',
    classId: { _id: 'class_3_id', name: 'Class 3' },
    sectionId: { _id: 'sec_3_b_id', name: 'Section B' },
    bloodGroup: 'O+',
    emergencyContact: '+91 98765 43210',
    medicalNotes: 'No known allergies or chronic conditions.',
    studentPhoto: '/ananya-student.jpg',
    enrollmentDate: new Date('2022-06-10T00:00:00.000Z'),
    status: 'Active',
    parentId: '66789abcdef0123456789abc',
    teacherName: 'Mr. Rajesh Kumar',
    attendanceRate: 96.8,
    pendingHomework: 1,
    feesDue: 4000,
    recentActivity: 'Science Lab Plant Photosynthesis Experiment',
  },
];

export const FALLBACK_DIARIES = [
  {
    _id: 'diary_aarav_1',
    studentId: {
      _id: 'c10101010101010101010101',
      firstName: 'Aarav',
      lastName: 'Sharma',
      grade: 'LKG',
      section: 'A',
    },
    teacherId: {
      _id: 't1',
      firstName: 'Ms. Ananya',
      lastName: 'Roy',
    },
    date: new Date('2026-09-18T00:00:00.000Z'),
    mood: 'Happy',
    meals: [
      { type: 'Morning Snack', status: 'Ate full portion of papaya and almond cookies' },
      { type: 'Lunch', status: 'Finished complete warm meal (dal khichdi, curd, cucumber)' },
    ],
    napTime: { duration: '45 mins' },
    activities: [
      'Phonics letter sound /m/ & /s/ tactile card matching',
      'Clay animal modeling & fine motor sensory play',
      'Outdoor sandpit exploration with balancing beams',
    ],
    notes: 'Aarav was exceptionally cheerful during circle time story session. Shared crayons kindly with classmates.',
  },
  {
    _id: 'diary_ananya_1',
    studentId: {
      _id: 'c20202020202020202020202',
      firstName: 'Ananya',
      lastName: 'Sharma',
      grade: 'Class 3',
      section: 'B',
    },
    teacherId: {
      _id: 't2',
      firstName: 'Mr. Rajesh',
      lastName: 'Kumar',
    },
    date: new Date('2026-09-18T00:00:00.000Z'),
    mood: 'Happy',
    meals: [
      { type: 'Lunch', status: 'Finished wholesome lunch box' },
      { type: 'Afternoon Snack', status: 'Roasted makhana and apple slices' },
    ],
    napTime: { duration: 'N/A (Senior Primary)' },
    activities: [
      'Science Lab: Plant cell observation under microscope',
      'Mathematics: 3-digit mental multiplication sprint',
      'Library: Borrowed "The Secret Garden" for weekend reading',
    ],
    notes: 'Ananya scored full marks in the Mental Math pop quiz today! Commended for clear blackboard explanation.',
  },
];

export const FALLBACK_ATTENDANCE = [
  {
    _id: 'att_aarav_today',
    entityId: {
      _id: 'c10101010101010101010101',
      firstName: 'Aarav',
      lastName: 'Sharma',
      grade: 'LKG',
      name: 'Aarav Sharma',
      classId: { _id: 'class_lkg_id', name: 'LKG' },
      sectionId: { _id: 'sec_lkg_a_id', name: 'Section A' },
    },
    entityType: 'Student',
    status: 'Present',
    date: new Date('2026-09-18T03:00:00.000Z'),
    markedBy: { _id: 't1', firstName: 'Ms. Ananya', lastName: 'Roy' },
    remarks: 'Punctual (08:24 AM) • Temperature 98.4°F normal',
  },
  {
    _id: 'att_ananya_today',
    entityId: {
      _id: 'c20202020202020202020202',
      firstName: 'Ananya',
      lastName: 'Sharma',
      grade: 'Class 3',
      name: 'Ananya Sharma',
      classId: { _id: 'class_3_id', name: 'Class 3' },
      sectionId: { _id: 'sec_3_b_id', name: 'Section B' },
    },
    entityType: 'Student',
    status: 'Present',
    date: new Date('2026-09-18T03:00:00.000Z'),
    markedBy: { _id: 't2', firstName: 'Mr. Rajesh', lastName: 'Kumar' },
    remarks: 'Punctual (08:18 AM)',
  },
];

export const FALLBACK_FEES = [
  {
    _id: 'fee_aarav_term2',
    studentId: {
      _id: 'c10101010101010101010101',
      firstName: 'Aarav',
      lastName: 'Sharma',
      grade: 'LKG',
      admissionNumber: 'GGPS-2024-089',
    },
    grade: 'LKG',
    feeType: 'Tuition',
    title: 'Term 2 Tuition & Activity Fee',
    totalAmount: 28500,
    amount: 28500,
    amountPaid: 28500,
    paidAmount: 28500,
    dueDate: new Date('2026-08-15T00:00:00.000Z'),
    status: 'Paid',
    paymentMethod: 'UPI / NetBanking',
    transactionId: 'TXN-GGPS-984210',
    invoiceNumber: 'INV-2026-0842',
    paidAt: new Date('2026-08-10T11:20:00.000Z'),
  },
  {
    _id: 'fee_ananya_term2',
    studentId: {
      _id: 'c20202020202020202020202',
      firstName: 'Ananya',
      lastName: 'Sharma',
      grade: 'Class 3',
      admissionNumber: 'GGPS-2022-042',
    },
    grade: 'Class 3',
    feeType: 'Tuition',
    title: 'Term 2 Composite Tuition & Science Lab Fee',
    totalAmount: 34000,
    amount: 34000,
    amountPaid: 34000,
    paidAmount: 34000,
    dueDate: new Date('2026-08-15T00:00:00.000Z'),
    status: 'Paid',
    paymentMethod: 'Credit Card',
    transactionId: 'TXN-GGPS-984255',
    invoiceNumber: 'INV-2026-0845',
    paidAt: new Date('2026-08-12T14:45:00.000Z'),
  },
  {
    _id: 'fee_aarav_term3',
    studentId: {
      _id: 'c10101010101010101010101',
      firstName: 'Aarav',
      lastName: 'Sharma',
      grade: 'LKG',
      admissionNumber: 'GGPS-2024-089',
    },
    grade: 'LKG',
    feeType: 'Tuition',
    title: 'Term 3 Tuition & Early Learning Kit',
    totalAmount: 28500,
    amount: 28500,
    amountPaid: 0,
    paidAmount: 0,
    dueDate: new Date(Date.now() + 14 * 86400000),
    status: 'Pending',
    invoiceNumber: 'INV-2026-1120',
  },
  {
    _id: 'fee_ananya_term3',
    studentId: {
      _id: 'c20202020202020202020202',
      firstName: 'Ananya',
      lastName: 'Sharma',
      grade: 'Class 3',
      admissionNumber: 'GGPS-2022-042',
    },
    grade: 'Class 3',
    feeType: 'Tuition',
    title: 'Term 3 Composite Tuition & Annual Fest Fee',
    totalAmount: 34000,
    amount: 34000,
    amountPaid: 0,
    paidAmount: 0,
    dueDate: new Date(Date.now() + 14 * 86400000),
    status: 'Pending',
    invoiceNumber: 'INV-2026-1124',
  },
];

export const FALLBACK_ASSESSMENTS = [
  {
    _id: 'assess_aarav_1',
    childId: {
      _id: 'c10101010101010101010101',
      firstName: 'Aarav',
      lastName: 'Sharma',
      grade: 'LKG',
    },
    title: 'Term 1 Early Developmental Milestone Assessment',
    category: 'Cognitive & Motor',
    date: new Date('2026-08-25T00:00:00.000Z'),
    overallGrade: 'Exceeding Expectations',
    teacherNotes: 'Exceptional visual curiosity and empathetic social manners.',
    rubrics: [
      { skill: 'Fine Motor Coordination', rating: 'Advanced' },
      { skill: 'Phonics & Letter Recognition', rating: 'Proficient' },
      { skill: 'Social & Emotional Sharing', rating: 'Advanced' },
    ],
  },
  {
    _id: 'assess_ananya_1',
    childId: {
      _id: 'c20202020202020202020202',
      firstName: 'Ananya',
      lastName: 'Sharma',
      grade: 'Class 3',
    },
    title: 'Term 1 Comprehensive Academic Evaluation',
    category: 'Summative',
    date: new Date('2026-08-28T00:00:00.000Z'),
    overallGrade: 'A+ (94%)',
    teacherNotes: 'Consistent high performer with outstanding verbal articulation.',
    rubrics: [
      { skill: 'Mathematics & Logical Thinking', rating: '96%' },
      { skill: 'Science & Environmental Concepts', rating: '93%' },
      { skill: 'English Language & Creative Composition', rating: '95%' },
    ],
  },
];
